### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by zuacubd** [cvangysel/pyndri#1]
I can't compile the project. It gives the following error:
`src/pyndri.cpp:8:42: fatal error: indri/CompressedCollection.hpp: No such file or directory`

**Comment by zuacubd** [comment]
I solved this problem by adding the indri's include dir to the setup.py file. It was successfully built. But, new problem comes up. When I try to import the pyndri into python interpreter, it gives the following error: 
`lib/python2.7/site-packages/pyndri.so: undefined symbol: _ZTVN5indri5index9DiskIndexE`
would you please help me?

**Comment by cvangysel** [comment]
Could you try removing the build directory in the pyndri repository and any installed files (you'll have to figure out yourself where Python installs your packages)? I've seen this issue before and IIRC a clean start-over solved the issue.

**Comment by zuacubd** [comment]
I have changed the setup.py script a bit. Because, I installed indri in my local directory. setup.py script is now:
`from distutils.core import setup, Extension
pyndri = Extension(
    pyndri,
    sources=['src/pyndri.cpp'],
    include_dirs=['/home/arif/search_engine/indri/include'], #I added include directory of indri
    libraries=['z', 'pthread', 'm'], #I remove indri libraries. I don't understand what I should point for indri
    define_macros=[('P_NEEDS_GNU_CXX_NAMESPACE', '1')])

setup(name='pyndri',
      version='1.0',
      description='pyndri is a Python interface to the Indri search engine',
      author='Christophe Van Gysel',
      author_email='cvangysel@uva.nl',
      url='http://ilps.science.uva.nl',
      ext_modules=[pyndri])`

In my machine, Python installs packages in the following directory (local user directory, not system wide)
`/home/arif/python/lib/python2.7/site-packages/`
for example, `/home/arif/python/lib/python2.7/site-packages/pyndri.so`

Still same problem. Thank for your help.

**Comment by cvangysel** [comment]
You removed indri from the libraries you are linking against. How can you expect this interface to work if you are not linking against the library it is supposed to interface with?

You should add indri again to the libraries variable and make sure the linker can pick up on the compiled library. You can correctly set-up your system, or you can quick-fix this by setting library_dirs=['/home/arif/search_engine/indri/lib'].

**Comment by thiziri** [comment]
I'm using Anaconda 3 and want to use pyndri but I don't know where can I add pyndry (I downloaded the Pyndry-Master) but How can I integrate it to gensim on Anaconda ?

**Comment by cvangysel** [comment]
For future reference, please don't resurrect old threads.

You can try the instructions posted here: https://github.com/cvangysel/pyndri/issues/6#issuecomment-274760769

**Comment by thiziri** [comment]
Thanks, but I'm using Windows :( How can I resolve it so ?

**Comment by cvangysel** [comment]
Unfortunately I hadn't had the need yet to run this on Windows. I'm afraid you're on your own in this case.

**Comment by thiziri** [comment]
Ok, thanks I'll try to make it on Linux, thank you for responding my question.
