### ISSUE TITLE
How can a get content of document

### ISSUE THREAD

**Issue by taufikridwan** [cvangysel/pyndri#10]
i try to get content (text in document which i index), but is failure to get it

> import pyndri
> 
> index = pyndri.Index('/home/opiq/indri/runquery/alQuran/indeks')
> dictionary = pyndri.extract_dictionary(index)
> _, int_doc_id = index.document_ids([' QS_1:1 '])
> print([dictionary[token_id]
> 	for token_id in index.document(int_doc_id)[1]])

but i get error

```
> Traceback (most recent call last):
>   File "contoh-dok.py", line 5, in <module>
>     _, int_doc_id = index.document_ids([' QS_1:1 '])
> ValueError: not enough values to unpack (expected 2, got 0)
```

thanks if for your answer

**Comment by taufikridwan** [comment]
with this code i get index of document,

> for int_document_id, score in results:
>     ext_document_id, _ = index.document(int_document_id)
>     print(ext_document_id, score)
>     print(index.document(int_document_id))

but, i want get document content

**Comment by cvangysel** [comment]
`index.document` returns a pair where the first element is the external document identifier and the second element is a tuple of token identifiers (i.e., the document content). The token identifiers can be translated back into strings through the [dictionary](https://github.com/cvangysel/pyndri/blob/master/examples/dictionary.py).
