### ISSUE TITLE
InstallationError : Failed building the wheel

### ISSUE THREAD

**Issue by Gracelek** [cvangysel/pyndri#12]
I updated gcc using brew and installed indri.
But when installing pyndri, it gives the error, Failed building the wheel for pyndri
Do you know what's the problem?

**Comment by cvangysel** [comment]
Can you provide more details? E.g., the exact command and its output, etc.

**Comment by Gracelek** [comment]
I installed Indri-5.11 and used Brew to ___ gcc. 
When I try `sudo pip3 install pyndri`, it gives the error below in the file.
[pyndri_install_output.txt](https://github.com/cvangysel/pyndri/files/1416755/pyndri_install_output.txt)

**Comment by cvangysel** [comment]
If you look at the output, you can see that the compilation errors occur within the Indri code base. If you were able to successfully compile Indri, then the most likely explanation for this error is that pip is picking up a different compiler than the one you used to compile Indri with. In fact, it says explicitly in the logs that clang is used as compiler.

I'd suggest trying again with the following command:

    CC=gcc CXX=g++ sudo -E pip3 install pyndri

The `-E` flag passed to `sudo` preserves your environment.

Let me know if this works for you.

**Comment by Gracelek** [comment]
Thank you for the prompt response.
It still gives the similar error message even if it uses gcc as Indri complier.
Here is the error message of several tryings including your suggestion.
[pyndri_clang_gcc.txt](https://github.com/cvangysel/pyndri/files/1416918/pyndri_clang_gcc.txt)

**Comment by cvangysel** [comment]
Ah, I see. I didn't see at first that you're running this on a Macbook. Apple ships macOS with Clang by default, and adds symlinks from `/usr/bin/g++` and `/usr/bin/gcc` to the `clang` binary. So in fact, you are still compiling with Clang.

The GCC compiler installed by Homebrew typically can be invoked using `gcc-$VERSION` where `$VERSION` is likely 5, 6 or 7.

On my system, I have GCC 5 installed using Homebrew and the following works for me:

    CC=gcc-5 CXX=g++-5 sudo -E pip3 install pyndri

**Comment by Gracelek** [comment]
I have GCC 7 and I tried with this but it returned the error.
[Pyndri_diff_error_using_gcc7.txt](https://github.com/cvangysel/pyndri/files/1418092/Pyndri_diff_error_using_gcc7.txt)
But I installed brew GCC 5 and finally Pyndri-0.1 is successfully installed.
Thank you for the help.
