### ISSUE TITLE
Pseudo relevance feedback

### ISSUE THREAD

**Issue by zuacubd** [cvangysel/pyndri#14]
Is pseudo relevance feedback based retrieval possible in pyndri?
All the examples that I see are related to without query expansion.

Thanks in advance

**Comment by cvangysel** [comment]
I haven't exposed the Indri PRF API within Pyndri, although I've seen forks that have this functionality (e.g., https://github.com/teanalab/pyndri/commit/e9a26cbc74b6756a359b247ee0d85a38afbfb8d5).

I'd be open to a PR that adds this functionality to the main repository.

**Comment by zuacubd** [comment]
Thank you very much for your reply. 
Looking for this functionality.

**Comment by cvangysel** [comment]
The latest commit (https://github.com/cvangysel/pyndri/commit/981e59f34c8d35c202cc40b7e2c19d2efc93d8ed) now enables PRF within pyndri. Let me know any feedback you may have.
