### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ortasa** [cvangysel/pyndri#16]
Hi, 
I try to install indri on my local folder at linux (I have no sudo rights).
When I run the command: "CC=gcc CXX=g++ pip3 install pyndri --user". 
I get this error: 
"  g++ -pthread -shared build/temp.linux-x86_64-3.5/src/pyndri.o -lindri -lz -lpthread -lm -o build/lib.linux-x86_64-3.5/pyndri_ext.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lindri
    collect2: ld returned 1 exit status
    error: command 'g++' failed with exit status 1

    ----------------------------------------
Command "/lv_local/home/ortal.as/python/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_fastrzt/pyndri/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qlf7fpqe-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-_fastrzt/pyndri/"

The installation log in the attached file:
[Installation Log.txt](https://github.com/cvangysel/pyndri/files/1614277/Installation.Log.txt)

I would be grateful if you had an idea how to solve the problem.
Thanks in advance,
Ortal

**Comment by ortasa** [comment]
After I updated all the below environment variables, the installation went smoothly:

export CPATH=/lv_local/home/ortal.as/indri-install/include
export LD_INCLUDE_PATH=/lv_local/home/ortal.as/indri-_install/lib
export LD_LIBRARY_PATH=/lv_local/home/ortal.as/indri-install/lib

Thanks, 
Ortal

**Comment by CSQianDong** [comment]
Works for me too! Thanks
