### ISSUE TITLE
Number of total docs is wrong (index.document_count())

### ISSUE THREAD

**Issue by littlewine** [cvangysel/pyndri#17]
Just a small detail:
The number of total docs is defined in index.document_count() is -1 of what it should be.

For instance, if max_document is 2 and document_base is 1, then the total # docs should be 2 instead of 1.
Hence, I believe the right formula is:
`index.document_count() = ( index.maximum_document() - index.document_base() +1 )`

**Comment by cvangysel** [comment]
I believe you are incorrect. The internal document identifier is inclusive of the base id, but exclusive the maximum document id.

First of all, please use the tests to showcase this bug. In fact, there is a test checking this behaviour and it passes with the current implementation: https://github.com/cvangysel/pyndri/blob/master/tests/pyndri_tests.py#L144

Secondly, I used (a) `pyndri` to get the document count and (b) Indri's `dumpindex` tool.

Using `pyndri`:

    $ python
    >>> import pyndri
    >>> index = pyndri.Index('/home/cvangysel/adhoc-data/index/trec-adhoc/ap_88_89/index')
    >>> len(index)
    164597
    >>> index.document_count()
    164597

Using `dumpindex`:

    $ dumpindex /home/cvangysel/adhoc-data/index/trec-adhoc/ap_88_89/index stats
    Repository statistics:
    documents:	164597

Where exactly is the problem?

**Comment by littlewine** [comment]
Sorry, apparently I missinterpreted the `index.maximum_document()` 

> >>> index.maximum_document()
> 164598

I thought it was an existing document id, rather than the next document id to be added in the index.

**Comment by cvangysel** [comment]
No problem; closing this issue.
