### ISSUE TITLE
The stemmer option are not available

### ISSUE THREAD

**Issue by ortasa** [cvangysel/pyndri#18]
Good Morning,

I installed the latest pyndri today (5.2.18). 
Options from the example stem.py (krovetz_stem, porter_stem) are not available. The only available option is "stem". 

Thannk you in advance,
Ortal

**Comment by cvangysel** [comment]
The API changed recently. The version on Pip uses the old API. You need to
clone the Git repository and install from there in order to get access to
the methods you’ve listed.

**Comment by cvangysel** [comment]
I've published a new version of pyndri on pip. You can upgrade as follows:

    pip install --upgrade pyndri

Let me know if you run into any more problems.
