### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by cyberpi78** [cvangysel/pyndri#2]
src/pyndri.cpp:8:42: fatal error: indri/CompressedCollection.hpp: No such file or directory
 #include <indri/CompressedCollection.hpp>
                                          ^
compilation terminated.
error: command 'x86_64-pc-linux-gnu-g++' failed with exit status 1

**Comment by cvangysel** [comment]
The compiler is unable to find your Indri installation, update your environment variables such that your compiler can find the headers/libraries.

For GCC on Linux, you should set CPATH to include the "include" directory of your Indri installation, the same goes for LD_INCLUDE_PATH for the "lib" directory.

If you do not know which directories these are, then please consult the Indri installation guide or the manual for your Linux distribution. You can configure the build process with the --prefix flag to indicate where Indri should put these directories.

**Comment by cyberpi78** [comment]
I see. I did that and got this:

fatal error: lemur/lemur-platform.h: No such file or directory
 #include "lemur/lemur-platform.h"
                                  ^
compilation terminated.
error: command 'x86_64-pc-linux-gnu-g++' failed with exit status 1

---UPDATE---

I tried adding the path to lemur in CPATH and LD_INCLUDE_PATH and it did not work... I continue to get the same error I mentioned earlier. Is there a different variable for Lemur?

**Comment by cvangysel** [comment]
I'm closing this issue as this problem is not specific/due to pyndri.
