### ISSUE TITLE
Is it possible to use pyndri with index that was created by indri 5.6

### ISSUE THREAD

**Issue by ortasa** [cvangysel/pyndri#20]
Good evening, 
is it possible to use pyndri with index that was created by indri 5.6?
Thanks in advance, 
Ortal

**Comment by Braamling** [comment]
I'm not sure whether this will influence other functionalities of Pyndri, but I was able to load an Indri 5.8 index into Pyndri by changing the manifest of the index (make sure to backup the manifest into another directory).

Change the line: 
```
<indri-distribution>Indri development release 5.8</indri-distribution>
 ```
To 
```
<indri-distribution>indri version 5.11</indri-distribution>
```

**Comment by cvangysel** [comment]
This is an Indri-related question. Pyndri will link with whatever version of Indri that's installed on the machine. The question thus becomes one regarding Indri's backwards compatibility and can be best answered by the Indri developers.
