### ISSUE TITLE
Error while running "pip3 install pyndri"

### ISSUE THREAD

**Issue by thiziri** [cvangysel/pyndri#22]
Hi there,
While running the command "pip3 install pyndri" I've got the following error:

> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    src/pyndri.cpp:9:42: fatal error: antlr/NoViableAltException.hpp: No such file or directory
     #include <antlr/NoViableAltException.hpp>
                                              ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Command ".../python3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xqx2sa5u/pyndri/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0bhj1piv-record/install-record.txt --single-version-externally-managed --compile --install-headers .../python3.5/include/site/python3.5/pyndri" failed with error code 1 in /tmp/pip-build-xqx2sa5u/pyndri/

I've run the "install setuptools" command successfully.
Could you help me, please?
Best regards

**Comment by cvangysel** [comment]
This indicates that the Indri header files cannot be found. Was Indri installed properly? If you installed Indri in a non-standard location, you'll need to set your `CPATH` and `LD_LIBRARY_PATH` environment variables to reflect this.

**Comment by thiziri** [comment]
Yes, I've installed INDRI. I'll try setting the environment variables.
Thanks 
The problem is solved by setting the environment variables, you can close this issue.
Thanks again.
