### ISSUE TITLE
How can i connect indri to mongodb 

### ISSUE THREAD

**Issue by Rebaiahmed** [cvangysel/pyndri#23]
Hello everyone i want to index my collection of data imported into mongodb database 
how can i connect indri tto index mongodb data ? 
or how can i use pyndri to connect to mongodb ?

**Comment by cvangysel** [comment]
AFAIK, you cannot directly index data from a MongoDB database. You'll have to dump the data into a format that Indri can understand and then index it that way.

Pyndri is a read-only tool to query Indri indexes from within Python. Indri-related questions can be asked [here](https://sourceforge.net/projects/lemur/support).
