### ISSUE TITLE
Little Help

### ISSUE THREAD

**Issue by avieini** [cvangysel/pyndri#24]
Hi,
I'm new to pyndri and I was wondering if I could use a little help here.
I want to extract from the index the words vectors of documents that contain a specific word (e.g. extract all of the words-vector of the documents contain the word, Asia). Is there any convenient way to extract this information by pyndri?
In addition, I want to run an RM3 model. how can I do that?
Thank a lot!

**Comment by cvangysel** [comment]
Direct access to the inverted index structure currently isn't supported. However, it shouldn't be hard to add. If you implement it, please send a PR and we can see to whether we can get this merged in.

An example using RM3 can be found here: https://github.com/cvangysel/pyndri/blob/master/examples/query_environments.py#L24
