### ISSUE TITLE
Request for sample code to use the weighted sequential dependence model with pyndri ?

### ISSUE THREAD

**Issue by se4u** [cvangysel/pyndri#26]
Hi, I am wondering whether it is possible to use the WSDM with pyndri ? Do you have any sample code for this use case ? Also is it possible to do parameter tuning using pyndri ?

**Comment by cvangysel** [comment]
I'm not entirely familiar with the WSD model. However, in the paper the authors note that they use Indri for initial retrieval. Indri supports unigram, bigram and unordered window matching, which are used within the WSD model.

A large part of the WSD model can probably be formulated as an Indri query. If you manage to create an example, please send a PR and we can see to get this checked in.
