### ISSUE TITLE
Is it possible to use field through Pyndri

### ISSUE THREAD

**Issue by ortasa** [cvangysel/pyndri#27]
Good morning, 

Thank you for all the good work you do.
Is it possible to use field through Pyndri? 

Thanks,
Ortal

**Comment by cvangysel** [comment]
Through pyndri, you can submit any query that would work with Indri. The Indri Query Language supports fielded retrieval (see https://sourceforge.net/p/lemur/wiki/Fields%20and%20Metadata/ for starters).

Direct support to the field information, however, is not supported at this time. If you manage to implement this functionality, please send me a PR.
