### ISSUE TITLE
Is there a interface to set retrieval model (Language model or BM25)?

### ISSUE THREAD

**Issue by Chrisdy** [cvangysel/pyndri#3]
Very glad to see your work, I keep looking for a python interface for Indri since I am not good at C++. I have read your example code carefully, it seems that there are no function to set retrieval model and smoothing parameters. Could you add functions for those?

**Comment by cvangysel** [comment]
Yes, we added functions for these in our latest release.

You can now import TFIDFQueryEnvironment, OkapiQueryEnvironment and QueryEnvironment from pyndri (see definition here: https://github.com/cvangysel/pyndri/blob/master/py/__init__.py#L83).

Code snippet 4 in the overview paper (https://arxiv.org/abs/1701.00749) shows how to use QueryEnvironment.
