### ISSUE TITLE
setup error on Ubuntu system

### ISSUE THREAD

**Issue by sherlockhoatszx** [cvangysel/pyndri#5]
Hi,
Many thanks for your contributing, that could be very useful.  I clone the 'pyndri' to my computer,and run 'sudo python setup.py install' error report:
- system: ubuntu
- run 'sudo python setup.py install'
- error report is : running install
running build
running build_py
running build_ext
building 'pyndri_ext' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -DP_NEEDS_GNU_CXX_NAMESPACE=1 -UNDEBUG -I/usr/include/python2.7 -c src/pyndri.cpp -o build/temp.linux-x86_64-2.7/src/pyndri.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
src/pyndri.cpp:8:42: fatal error: antlr/NoViableAltException.hpp: 没有那个文件或目录
 #include <antlr/NoViableAltException.hpp>
                                          ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

- what i have tried: i try to install dependency package like 

> sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev

> sudo easy_install greenlet

> sudo easy_install gevent 
> sudo pip install lxml --upgrade

- then those seems didn't work , still report error the same as above.

**Comment by cvangysel** [comment]
Thanks for your report. Please first install Indri (https://www.lemurproject.org/indri.php) before attempting to install pyndri. You can download Indri here: https://sourceforge.net/projects/lemur/files/lemur/indri-5.10/
