### ISSUE TITLE
Undefined Symbol on import (not the one in the FAQ)

### ISSUE THREAD

**Issue by Noxeus** [cvangysel/pyndri#6]
I build and installed `indri` (latest) and installed pyndri for `python3.5` but when I try to `import pyndri` it gives the following error:

```
In [1]: import pyndri
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-601147fcfd90> in <module>()
----> 1 import pyndri

/usr/local/lib/python3.5/dist-packages/pyndri-1.0-py3.5-linux-x86_64.egg/pyndri/__init__.py in <module>()
      1 from pyndri.dictionary import Dictionary, extract_dictionary
      2 
----> 3 from pyndri_ext import Index as __IndexBase
      4 from pyndri_ext import QueryEnvironment, stem, tokenize
      5 

ImportError: /usr/local/lib/python3.5/dist-packages/pyndri-1.0-py3.5-linux-x86_64.egg/pyndri_ext.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5indri3api16QueryEnvironment8addIndexERKSs
```

I'm using `Linux Mint 18 Sarah x64` with  `Python 3.5.2` and I build `Indri` and `Pyndri` using the following commands:
for `Indri` after `tar xvzf`:
`./configure`
`make`
`sudo make install`

for `Pyndri`:
`sudo python3 setup.py install`

The error is produced directly after attempting to `import pyndri` in python3.
I can't really make much out of the error code, any help please?

**Comment by cvangysel** [comment]
What system are you running on?

**Comment by cvangysel** [comment]
Can you give the complete sequence of commands (including how you installed Indri) that caused this behaviour?

**Comment by Noxeus** [comment]
I edited my question to include the system and build/installation commands.

**Comment by cvangysel** [comment]
What compiler was used to compile Indri/pyndri? Also, your traceback shows that you're using ipython. Does the same error happen in regular python3 as well?

**Comment by DavidvanErkelens** [comment]
I am experiencing the same issue - same OS, same setup and same set of commands. As compiler, I am using the default gcc and the error also happens in the regular python3:

```
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyndri
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyndri/__init__.py", line 3, in <module>
    from pyndri_ext import Index as __IndexBase
ImportError: /usr/local/lib/python3.5/dist-packages/pyndri_ext.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5indri3api16QueryEnvironment8addIndexERKSs
```

**Comment by cvangysel** [comment]
Here's a silly approach that fixed the problem for someone else with a similar issue. Go the pyndri directory and:

    rm -Rf build/
    python setup.py install

Apparently compiling twice is better than once. Be sure to remove the `build/` folder, as otherwise compilation will not be triggered.

**Comment by Noxeus** [comment]
I'm afraid this didn't do the trick for me. I already tried multiple compiles, and tried it again today.
Still an error on import.
I'll just drop Pyndri for now.

**Comment by cvangysel** [comment]
I downloaded a Mint 18 Sarah VM from osboxes.org and was able to install pyndri without any problems.

First, install dependencies:

    sudo apt install g++ zlib1g-dev python3.5-dev python3-pip
    sudo pip3 install setuptools

Here's the commands I used for Indri:

    wget <url-to-indri-5.11.tar.gz>
    tar xzvf indri-5.11.tar.gz
    cd indri-5.11
    ./configure CXX="g++ -D_GLIBCXX_USE_CXX11_ABI=0"
    make
    sudo make install

and, finally, for pyndri:

    sudo pip3 install pyndri

Afterwards, I can `import pyndri` without any issues.

**Comment by thiziri** [comment]
Good morning,
I'm using Ubuntu16.04 and python3.5, I successfully installed Indri
I followed the different steps to install "pyndri" but I've got the following error while importing it : 
`Segmentation fault (core dumped)` 
Do you have an idea please ?
Thanks

**Comment by thiziri** [comment]
Good morning,
You can delete my comment I resolved the problem, I've just made : 
`pip3 install --user pyndri`
It was a problem of permission
Thanks
