### ISSUE TITLE
Access the BM25 implementation 

### ISSUE THREAD

**Issue by thiziri** [cvangysel/pyndri#7]
Good morning;
I need to my experiments to access the implementation of the BM25 model because I have to perform some changes to my model, please, how can I get access to the BM25 implementation in order to make my experiments, or call the function making the BM25 ?
Thanks

**Comment by cvangysel** [comment]
I added an example on how to do this here:

https://github.com/cvangysel/pyndri/blob/master/examples/query_environments.py

Be sure to check the Indri documentation for the exact flavour of TFIDF/BM25 you are getting.

Good luck!

**Comment by thiziri** [comment]
Thanks :)

**Comment by taufikridwan** [comment]
i succes in running simple code

```
import pyndri

index = pyndri.Index('/home/opiq/indri/runquery/alfatihah_indeks')

# Queries the index with 'hello world' and returns the first 1000 results.
results = index.query('#wsum (2.0 #1(bismil))', results_requested=1000)

for int_document_id, score in results:
    ext_document_id, _ = index.document(int_document_id)
    print(ext_document_id, score)
```

and get result just like this 
`doc_1`  -3.357361315536498

then,i try to run query again with example query_environments.py 

with this code
```
import pyndri
import sys

if len(sys.argv) <= 1:
    print('Usage: python {0} </home/opiq/indri/runquery/alfatihah_indeks>'.format(sys.argv[0]))

    sys.exit(0)

with pyndri.open(sys.argv[1]) as index:
    # Constructs a QueryEnvironment that uses a
    # language model with Dirichlet smoothing.
    lm_query_env = pyndri.QueryEnvironment(
        index, rules=('method:dirichlet,mu:5000',))
    print(lm_query_env.query('bismil'))

    # Constructs a QueryEnvironment that uses the TF-IDF retrieval model.
    #
    # See "Baseline (non-LM) retrieval"
    # (https://lemurproject.org/doxygen/lemur/html/IndriRunQuery.html)
    tfidf_query_env = pyndri.TFIDFQueryEnvironment(index)
    print(tfidf_query_env.query('bismil'))

    # Constructs a QueryEnvironment that uses the Okapi BM25 retrieval model.
    #
    # See "Baseline (non-LM) retrieval"
    # (https://lemurproject.org/doxygen/lemur/html/IndriRunQuery.html)
    bm25_query_env = pyndri.OkapiQueryEnvironment(index)
    print(bm25_query_env.query('bismil'))
```

and get result like this

> Usage:python query_environments.py </home/opiq/indri/runquery/alfatihah_indeks>

How can i get such results simple code but with parameter like query_environments.py
