### ISSUE TITLE
Error Run sample code

### ISSUE THREAD

**Issue by taufikridwan** [cvangysel/pyndri#9]
i have run this code:
sudo apt install g++ zlib1g-dev python3.5-dev python3-pip
sudo pip3 install setuptools

i have run this code too:
./configure CXX="g++ -D_GLIBCXX_USE_CXX11_ABI=0"
make
sudo make install

and then i try to run example code in pyndri

import pyndri

index = pyndri.Index('~/indri-5.11/runquery/alQuran/indeks')

for document_id in range(index.document_base(), index.maximum_document()):
    print(index.document(document_id))

and get error in 

> Traceback (most recent call last):
>   File "opik.py", line 3, in <module>
>     index = pyndri.Index('~/indri-5.11/runquery/alQuran/indeks')
>   File "/usr/local/lib/python3.5/site-packages/pyndri/__init__.py", line 46, in __init__
>     super(Index, self).__init__(*args, **kwargs)
> OSError: ../src/Parameters.cpp(469): Couldn't open parameter file '~/indri-5.11/runquery/alQuran/indeks/manifest' for reading.

what should i do,, i am newby in python and pyndri.. thanks for your answer

**Comment by cvangysel** [comment]
I suspect this is because you are using the tilde (~) to reference your home directory. AFAIK, this only works in shells. Try using the full path (i.e., /home/<USERNAME>/indri-5.11/...) instead.

**Comment by taufikridwan** [comment]
error still same..
Traceback (most recent call last):
  File "opik.py", line 3, in <module>
    index = pyndri.Index('/home/indri-5.11/runquery/alQuran/indeks')
  File "/usr/local/lib/python3.5/site-packages/pyndri/__init__.py", line 46, in __init__
    super(Index, self).__init__(*args, **kwargs)
OSError: ../src/Parameters.cpp(469): Couldn't open parameter file '/home/indri-5.11/runquery/alQuran/indeks/manifest' for reading.

**Comment by cvangysel** [comment]
I don't believe that `/home/indri-5.11` is the same path as `~/indri-5.11`. Can you verify that the  `/home/indri-5.11/runquery/alQuran/indeks` directory exists?

**Comment by taufikridwan** [comment]
it's exist because i have created that indeks document in indri... i'm not sure about installation that i do. i confused to try example code in pyndri,, i try test code in pyndri and still error:

> ~/pyndri-master/tests$ python pyndri_tests.py 
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
Fkstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
Fkstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
Fkstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
Fkstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
.kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
kstem_add_table_entry: Duplicate word emeritus will be ignored.
..kstem_add_table_entry: Duplicate word emeritus will be ignored.
..
======================================================================
FAIL: test_okapi (__main__.IndriTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyndri_tests.py", line 280, in test_okapi
    ((1, 0.691753771033259),))
AssertionError: Tuples differ: ((1, 0.6917537710332589),) != ((1, 0.691753771033259),)

First differing element 0:
(1, 0.6917537710332589)
(1, 0.691753771033259)

- ((1, 0.6917537710332589),)
?                      -

+ ((1, 0.691753771033259),)

======================================================================
FAIL: test_query_snippets (__main__.IndriTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyndri_tests.py", line 180, in test_query_snippets
    'Lorem IPSUM dolor sit amet, consectetur '
AssertionError: Tuples differ: ((1, -6.373564749941116, 'Lorem IPSUM dolor sit amet, consectet[27 chars].'),) != ((1, -6.373564749941117, 'Lorem IPSUM dolor sit amet, consectet[27 chars].'),)

First differing element 0:
(1, -6.373564749941116, 'Lorem IPSUM dolor sit amet, consectet[25 chars]...')
(1, -6.373564749941117, 'Lorem IPSUM dolor sit amet, consectet[25 chars]...')

  ((1,
-   -6.373564749941116,
?                    ^

+   -6.373564749941117,
?                    ^

    'Lorem IPSUM dolor sit amet, consectetur adipiscing\nelit. Duis...'),)

======================================================================
FAIL: test_simple_query (__main__.IndriTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyndri_tests.py", line 153, in test_simple_query
    ((1, -6.373564749941117),))
AssertionError: Tuples differ: ((1, -6.373564749941116),) != ((1, -6.373564749941117),)

First differing element 0:
(1, -6.373564749941116)
(1, -6.373564749941117)

- ((1, -6.373564749941116),)
?                       ^

+ ((1, -6.373564749941117),)
?                       ^


======================================================================
FAIL: test_tfidf (__main__.IndriTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyndri_tests.py", line 273, in test_tfidf
    (3, 0.07757942488345955)))
AssertionError: Tuples differ: ((2, 0.16955104430709386), (3, 0.07757942488345958)) != ((2, 0.16955104430709383), (3, 0.07757942488345955))

First differing element 0:
(2, 0.16955104430709386)
(2, 0.16955104430709383)

- ((2, 0.16955104430709386), (3, 0.07757942488345958))
?                        ^                         ^

+ ((2, 0.16955104430709383), (3, 0.07757942488345955))
?                        ^                         ^


----------------------------------------------------------------------
Ran 20 tests in 3.821s

FAILED (failures=4)

**Comment by cvangysel** [comment]
Those errors are likely system-specific, but aren't critical as they seem to be mostly related to floating point precision (i.e., most of the errors are just there because some digits are slightly different). It seems that pyndri was correctly installed on your system.

All that I know is that `~/indri-5.11` and `/home/indri-5.11` are generally not the same directory.

**Comment by taufikridwan** [comment]
thanks for your answer, now my pyndri is right. my wrong is my indeks path... 
/home/opiq/indri-5.11/runquery/alfatihah_indeks
